server:
  port: 5000
  servlet:
    encoding:
      charset: utf-8
      force: true

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    open-in-view: false
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
      ddl-auto: create
    properties:
      '[hibernate.default_batch_fetch_size]': 100

logging:
  level:
    '[com.group.shopping]': INFO